footprint: [[-0.750, 0.365],[0.075, 0.365], [0.075, -0.365], [-0.750, -0.365]]
obstacle_range: 2.5
raytrace_range: 3.0
#robot_radius: ir_of_robot
inflation_radius: 1


observation_sources: laser_scan_sensor 
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}

