local_costmap:
    #SPENCER: 5/16 this was odom
    global_frame: enc_odom_frame
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05

#plugins:
#  - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
#  - {name: inflation, type: "costmap_2d::InflationLayer"}
